version: "3.7"
services:
  timemachine:
    image: mbentley/timemachine:smb
    restart: unless-stopped
    network_mode: "host"
    environment:
      - TM_USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - SHARE_NAME=TimeMachine
      - VOLUME_SIZE_LIMIT=${VOLUME_SIZE_LIMIT}
    volumes:
      - ${DATA_PATH}:/opt/${USERNAME}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    container_name: ${CONTAINER_NAME}
